// Mocks generated by Mockito 5.4.6 from annotations
// in uprm_professional_portfolio/test/matches_logic_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:uprm_professional_portfolio/mock/matches_local_repository.dart'
    as _i4;
import 'package:uprm_professional_portfolio/models/swipe_process.dart' as _i3;
import 'package:uprm_professional_portfolio/services/swipe_process_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SwipeProcessRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwipeProcessRepository extends _i1.Mock
    implements _i2.SwipeProcessRepository {
  MockSwipeProcessRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void insertSwipe(_i3.SwipeProcess? swipe) => super.noSuchMethod(
        Invocation.method(
          #insertSwipe,
          [swipe],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalRepository extends _i1.Mock implements _i4.LocalRepository {
  MockLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get Favorites => (super.noSuchMethod(
        Invocation.getter(#Favorites),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  set Favorites(List<Map<String, dynamic>>? value) => super.noSuchMethod(
        Invocation.setter(
          #Favorites,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insertFavorite(Map<String, dynamic>? favorite) => super.noSuchMethod(
        Invocation.method(
          #insertFavorite,
          [favorite],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFavorite() => super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<Map<String, dynamic>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<String> getSkills() => (super.noSuchMethod(
        Invocation.method(
          #getSkills,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<Map<String, dynamic>> getJobs() => (super.noSuchMethod(
        Invocation.method(
          #getJobs,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> getSeekers() => (super.noSuchMethod(
        Invocation.method(
          #getSeekers,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> getRecruiters() => (super.noSuchMethod(
        Invocation.method(
          #getRecruiters,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);
}
